// NeuroPeripheral Master – Case Database
export const CASES = {
  level1: [
    {
      id: "l1_01",
      level: 1,
      limb: "upper",
      title: "Déficit Motor no Membro Superior",
      motor_deficit: "Queda do punho (wrist drop) — incapacidade de estender punho e dedos",
      sensory_pattern: "Perda de sensibilidade na face dorsal do polegar e 1º espaço interdigital",
      reflex_change: "Reflexo braquiorradial diminuído",
      mechanism: "Fratura de úmero (terço médio) ou pressão prolongada na axila",
      diagnosis: "Lesão do Nervo Radial",
      nerve: "Nervo Radial",
      root: "C5-C8",
      plexus_segment: "Fascículo posterior",
      compression_site: "Sulco radial do úmero",
      explanation: "O nervo radial inerva todos os extensores do punho e dedos. Lesões no sulco radial causam wrist drop clássico, com preservação do tríceps (ramo proximal). A sensibilidade é perdida no dorso da mão e polegar.",
      options: ["Nervo Radial", "Nervo Mediano", "Nervo Ulnar", "Nervo Axillar"],
      correct: "Nervo Radial",
      visual: "wrist_drop",
      sensory_area: "dorsal_thumb"
    },
    {
      id: "l1_02",
      level: 1,
      limb: "upper",
      title: "Déficit Motor na Mão",
      motor_deficit: "Mão em bênção (hand of benediction) — incapacidade de fletir 2º e 3º dedos",
      sensory_pattern: "Perda de sensibilidade nos 3,5 dedos laterais (polegar, indicador, médio e metade do anular)",
      reflex_change: "Reflexo bicipital pode estar diminuído",
      mechanism: "Síndrome do túnel do carpo ou lesão no punho/cotovelo",
      diagnosis: "Lesão do Nervo Mediano",
      nerve: "Nervo Mediano",
      root: "C6-T1",
      plexus_segment: "Fascículos lateral e medial",
      compression_site: "Túnel do carpo",
      explanation: "O nervo mediano inerva os flexores dos dedos 1-3, músculos tenares e lumbricais I e II. A lesão causa a mão em bênção: ao tentar fechar o punho, o 2º e 3º dedos ficam estendidos. Atrofia tenar é sinal tardio.",
      options: ["Nervo Mediano", "Nervo Ulnar", "Nervo Radial", "Nervo Musculocutâneo"],
      correct: "Nervo Mediano",
      visual: "hand_benediction",
      sensory_area: "lateral_35_digits"
    },
    {
      id: "l1_03",
      level: 1,
      limb: "upper",
      title: "Garra nos Dedos Ulnares",
      motor_deficit: "Garra ulnar (4º e 5º dedos) — hiperextensão das MCF e flexão das IFP/IFD",
      sensory_pattern: "Perda de sensibilidade nos 1,5 dedos mediais (dedo mínimo e metade do anular)",
      reflex_change: "Sem alteração reflexa significativa",
      mechanism: "Trauma no cotovelo, fratura do epicôndilo medial ou compressão no túnel cubital",
      diagnosis: "Lesão do Nervo Ulnar",
      nerve: "Nervo Ulnar",
      root: "C8-T1",
      plexus_segment: "Fascículo medial",
      compression_site: "Sulco do nervo ulnar (cotovelo)",
      explanation: "O nervo ulnar inerva os músculos hipotênares, interósseos, lumbricais III e IV e adutor do polegar. A garra é mais evidente nos dedos 4 e 5 porque os lumbricais I e II (mediano) estão intactos. Sinal de Froment positivo.",
      options: ["Nervo Ulnar", "Nervo Mediano", "Nervo Radial", "Nervo Interósseo Anterior"],
      correct: "Nervo Ulnar",
      visual: "claw_hand",
      sensory_area: "medial_15_digits"
    },
    {
      id: "l1_04",
      level: 1,
      limb: "upper",
      title: "Paralisia do Deltóide",
      motor_deficit: "Incapacidade de abduzir o ombro acima de 15°, atrofia do deltóide",
      sensory_pattern: "Perda de sensibilidade no remendo (patch) lateral do ombro",
      reflex_change: "Sem alteração reflexa",
      mechanism: "Luxação anterior do ombro ou fratura do colo cirúrgico do úmero",
      diagnosis: "Lesão do Nervo Axilar",
      nerve: "Nervo Axilar",
      root: "C5-C6",
      plexus_segment: "Fascículo posterior",
      compression_site: "Espaço quadrilateral",
      explanation: "O nervo axilar emerge do fascículo posterior e atravessa o espaço quadrilateral, inervando o deltóide e redondo menor. A luxação anterior do ombro é a causa mais comum. O déficit motor principal é a abdução do ombro.",
      options: ["Nervo Axilar", "Nervo Radial", "Nervo Supraescapular", "Nervo Musculocutâneo"],
      correct: "Nervo Axilar",
      visual: "deltoid_paralysis",
      sensory_area: "lateral_shoulder_patch"
    },
    {
      id: "l1_05",
      level: 1,
      limb: "lower",
      title: "Pé Caído",
      motor_deficit: "Foot drop — incapacidade de dorsiflexão e eversão do pé",
      sensory_pattern: "Perda de sensibilidade no dorso do pé e entre 1º e 2º dedos",
      reflex_change: "Sem alteração reflexa significativa",
      mechanism: "Compressão na cabeça da fíbula (cruzar as pernas, imobilização gessada)",
      diagnosis: "Lesão do Nervo Fibular Comum",
      nerve: "Nervo Fibular Comum",
      root: "L4-S1",
      plexus_segment: "Divisão dorsal do nervo isquiático",
      compression_site: "Cabeça da fíbula",
      explanation: "O nervo fibular comum contorna a cabeça da fíbula, sendo vulnerável à compressão. Inerva os músculos da dorsiflexão (tibial anterior) e eversão (fibulares). Foot drop é o sinal clínico principal, com marcha escarvante.",
      options: ["Nervo Fibular Comum", "Nervo Tibial", "Nervo Isquiático", "Nervo Femoral"],
      correct: "Nervo Fibular Comum",
      visual: "foot_drop",
      sensory_area: "dorsal_foot"
    },
    {
      id: "l1_06",
      level: 1,
      limb: "lower",
      title: "Perda da Flexão Plantar",
      motor_deficit: "Incapacidade de flexão plantar e inversão do pé, marcha anormal",
      sensory_pattern: "Perda de sensibilidade na planta do pé e face plantar dos dedos",
      reflex_change: "Reflexo aquileu abolido",
      mechanism: "Trauma na região posterior da perna, síndrome do túnel do tarso",
      diagnosis: "Lesão do Nervo Tibial",
      nerve: "Nervo Tibial",
      root: "L4-S3",
      plexus_segment: "Divisão ventral do nervo isquiático",
      compression_site: "Túnel do tarso (tornozelo)",
      explanation: "O nervo tibial inerva os músculos do compartimento posterior da perna (gastrocnêmio, sóleo, tibial posterior) e intrínsecos do pé. A lesão causa perda da flexão plantar e abolição do reflexo aquileu. A sensibilidade plantar é perdida.",
      options: ["Nervo Tibial", "Nervo Fibular Comum", "Nervo Sural", "Nervo Isquiático"],
      correct: "Nervo Tibial",
      visual: "plantar_loss",
      sensory_area: "plantar_foot"
    }
  ],

  level2: [
    {
      id: "l2_01",
      level: 2,
      limb: "upper",
      title: "Radiculopatia Cervical",
      motor_deficit: "Fraqueza na flexão do cotovelo e extensão do punho",
      sensory_pattern: "Parestesia no polegar e face lateral do antebraço",
      reflex_change: "Reflexo bicipital e braquiorradial diminuídos",
      mechanism: "Hérnia de disco C5-C6 ou espondilose cervical",
      diagnosis: "Radiculopatia C6",
      nerve: "Raiz C6",
      root: "C6",
      nerve_or_root: "radiculopathy",
      plexus_segment: "Tronco superior",
      compression_site: "Forame intervertebral C5-C6",
      explanation: "C6 inerva o bíceps (flexão cotovelo), braquiorradial e extensores do punho. O dermátomo C6 cobre o polegar e face lateral do antebraço. O reflexo bicipital e braquiorradial são mediados por C5-C6. Diferencia-se da síndrome do túnel carpal pela distribuição proximal e alteração reflexa.",
      options_root: ["C5", "C6", "C7", "C8"],
      options_type: ["Neuropatia Periférica", "Radiculopatia"],
      correct_root: "C6",
      correct_type: "Radiculopatia",
      reflex_table: { "Bíceps": "C5-C6", "Braquiorradial": "C5-C6", "Tríceps": "C7", "Patelar": "L3-L4", "Aquileu": "S1" }
    },
    {
      id: "l2_02",
      level: 2,
      limb: "upper",
      title: "Fraqueza nos Extensores do Cotovelo",
      motor_deficit: "Fraqueza na extensão do cotovelo e punho, dificuldade para escrever",
      sensory_pattern: "Parestesia no dedo médio e face dorsal do antebraço",
      reflex_change: "Reflexo tricipital diminuído",
      mechanism: "Hérnia de disco C6-C7",
      diagnosis: "Radiculopatia C7",
      nerve: "Raiz C7",
      root: "C7",
      nerve_or_root: "radiculopathy",
      plexus_segment: "Tronco médio",
      compression_site: "Forame intervertebral C6-C7",
      explanation: "C7 é a raiz mais frequentemente afetada nas hérnias cervicais. Inerva o tríceps (extensão do cotovelo), flexores do punho e extensores dos dedos. O dermátomo C7 cobre o dedo médio e face posterior do braço. Reflexo tricipital é patognomônico.",
      options_root: ["C6", "C7", "C8", "T1"],
      options_type: ["Neuropatia Periférica", "Radiculopatia"],
      correct_root: "C7",
      correct_type: "Radiculopatia",
      reflex_table: { "Bíceps": "C5-C6", "Braquiorradial": "C5-C6", "Tríceps": "C7", "Patelar": "L3-L4", "Aquileu": "S1" }
    },
    {
      id: "l2_03",
      level: 2,
      limb: "lower",
      title: "Radiculopatia Lombar — Déficit Quadricipital",
      motor_deficit: "Fraqueza na extensão do joelho, dificuldade para subir escadas",
      sensory_pattern: "Parestesia na face medial da perna e tornozelo",
      reflex_change: "Reflexo patelar diminuído",
      mechanism: "Hérnia de disco L3-L4 ou estenose foraminal",
      diagnosis: "Radiculopatia L4",
      nerve: "Raiz L4",
      root: "L4",
      nerve_or_root: "radiculopathy",
      plexus_segment: "Plexo lombossacral",
      compression_site: "Forame intervertebral L3-L4",
      explanation: "L4 inerva o quadríceps (extensão do joelho) e tibial anterior (dorsiflexão). O dermátomo L4 cobre a face medial da perna e tornozelo. O reflexo patelar (L3-L4) é o mais importante. Diferencia-se da lesão femoral por incluir dorsiflexão e ter distribuição dermatomal específica.",
      options_root: ["L3", "L4", "L5", "S1"],
      options_type: ["Neuropatia Periférica", "Radiculopatia"],
      correct_root: "L4",
      correct_type: "Radiculopatia",
      reflex_table: { "Bíceps": "C5-C6", "Braquiorradial": "C5-C6", "Tríceps": "C7", "Patelar": "L3-L4", "Aquileu": "S1" }
    },
    {
      id: "l2_04",
      level: 2,
      limb: "lower",
      title: "Radiculopatia com Foot Drop",
      motor_deficit: "Fraqueza na dorsiflexão do pé e extensão do hálux",
      sensory_pattern: "Parestesia no dorso do pé e entre 1º e 2º dedos",
      reflex_change: "Sem alteração reflexa significativa",
      mechanism: "Hérnia de disco L4-L5",
      diagnosis: "Radiculopatia L5",
      nerve: "Raiz L5",
      root: "L5",
      nerve_or_root: "radiculopathy",
      plexus_segment: "Plexo lombossacral",
      compression_site: "Forame intervertebral L4-L5",
      explanation: "L5 inerva tibial anterior, extensor longo do hálux e glúteo médio. Importante: não possui reflexo próprio facilmente testável (diferencial com lesão do nervo fibular). O dermátomo L5 cobre o dorso do pé e espaço entre 1º-2º dedos. Sinal de Trendelenburg positivo indica envolvimento do glúteo médio.",
      options_root: ["L4", "L5", "S1", "S2"],
      options_type: ["Neuropatia Periférica", "Radiculopatia"],
      correct_root: "L5",
      correct_type: "Radiculopatia",
      reflex_table: { "Bíceps": "C5-C6", "Braquiorradial": "C5-C6", "Tríceps": "C7", "Patelar": "L3-L4", "Aquileu": "S1" }
    },
    {
      id: "l2_05",
      level: 2,
      limb: "lower",
      title: "Ciática com Abolição do Reflexo Aquileu",
      motor_deficit: "Fraqueza na flexão plantar e eversão do pé",
      sensory_pattern: "Parestesia na face lateral do pé e dedo mínimo",
      reflex_change: "Reflexo aquileu abolido",
      mechanism: "Hérnia de disco L5-S1 (mais comum)",
      diagnosis: "Radiculopatia S1",
      nerve: "Raiz S1",
      root: "S1",
      nerve_or_root: "radiculopathy",
      plexus_segment: "Plexo lombossacral",
      compression_site: "Forame intervertebral L5-S1",
      explanation: "S1 é a raiz mais frequentemente afetada nas hérnias lombares. Inerva o gastrocnêmio, sóleo e músculos fibulares. O reflexo aquileu (S1) é o marcador mais importante — sua abolição sugere lesão de S1. Dermátomo S1: face lateral do pé e calcâneo.",
      options_root: ["L4", "L5", "S1", "S2"],
      options_type: ["Neuropatia Periférica", "Radiculopatia"],
      correct_root: "S1",
      correct_type: "Radiculopatia",
      reflex_table: { "Bíceps": "C5-C6", "Braquiorradial": "C5-C6", "Tríceps": "C7", "Patelar": "L3-L4", "Aquileu": "S1" }
    }
  ],

  level3: [
    {
      id: "l3_01",
      level: 3,
      limb: "upper",
      title: "Lesão do Plexo Braquial Superior",
      motor_deficit: "Braço em 'posição de garçom' — perda de abdução, rotação externa e flexão do cotovelo",
      sensory_pattern: "Perda de sensibilidade na face lateral do braço e antebraço",
      reflex_change: "Reflexo bicipital e braquiorradial abolidos",
      mechanism: "Distócia de ombro ao nascimento, queda sobre o ombro com lateralização forçada da cabeça",
      diagnosis: "Paralisia de Erb (Tronco Superior C5-C6)",
      nerve: "Tronco Superior",
      root: "C5-C6",
      plexus_segment: "Tronco Superior",
      compression_site: "Ponto de Erb (3 cm acima da clavícula)",
      explanation: "A paralisia de Erb é a lesão mais comum do plexo braquial, afetando C5-C6. Resulta em paralisia do deltóide, bíceps, braquiorradial e supraespinhoso. A posição clássica é 'braço de garçom': adução, rotação interna, extensão do cotovelo e pronação. Prognóstico geralmente favorável.",
      options: ["Tronco Superior (C5-C6)", "Tronco Médio (C7)", "Tronco Inferior (C8-T1)", "Fascículo Posterior"],
      correct: "Tronco Superior (C5-C6)"
    },
    {
      id: "l3_02",
      level: 3,
      limb: "upper",
      title: "Lesão do Plexo Braquial Inferior",
      motor_deficit: "Mão em garra, fraqueza dos músculos intrínsecos da mão, síndrome de Horner ipsilateral",
      sensory_pattern: "Perda de sensibilidade na face medial do braço, antebraço e mão (dedos 4-5)",
      reflex_change: "Reflexo ulnar diminuído",
      mechanism: "Parto pélvico (braço elevado acima da cabeça), costela cervical, síndrome do desfiladeiro torácico",
      diagnosis: "Paralisia de Klumpke (Tronco Inferior C8-T1)",
      nerve: "Tronco Inferior",
      root: "C8-T1",
      plexus_segment: "Tronco Inferior",
      compression_site: "Ângulo costocervical",
      explanation: "A paralisia de Klumpke afeta C8-T1, comprometendo os músculos intrínsecos da mão (interósseos, hipotênares, lumbricais). A síndrome de Horner (ptose, miose, anidrose) indica envolvimento de T1 com fibras simpáticas. Mais grave que a paralisia de Erb.",
      options: ["Tronco Superior (C5-C6)", "Tronco Médio (C7)", "Tronco Inferior (C8-T1)", "Fascículo Lateral"],
      correct: "Tronco Inferior (C8-T1)"
    },
    {
      id: "l3_03",
      level: 3,
      limb: "upper",
      title: "Lesão do Fascículo Posterior",
      motor_deficit: "Fraqueza na extensão do cotovelo, punho e dedos + déficit de abdução do ombro",
      sensory_pattern: "Perda de sensibilidade no dorso da mão, face lateral do ombro",
      reflex_change: "Reflexo tricipital e braquiorradial diminuídos",
      mechanism: "Luxação do ombro, trauma axilar, uso de muleta axilar",
      diagnosis: "Lesão do Fascículo Posterior",
      nerve: "Fascículo Posterior",
      root: "C5-C8",
      plexus_segment: "Fascículo Posterior",
      compression_site: "Axila",
      explanation: "O fascículo posterior origina os nervos radial e axilar. Lesões causam déficit combinado: wrist drop (radial) + paralisia do deltóide (axilar). A extensão do cotovelo (tríceps/radial) também é comprometida. A causa mais comum é a luxação anterior do ombro.",
      options: ["Fascículo Lateral", "Fascículo Medial", "Fascículo Posterior", "Tronco Superior"],
      correct: "Fascículo Posterior"
    },
    {
      id: "l3_04",
      level: 3,
      limb: "lower",
      title: "Plexopatia Lombossacral",
      motor_deficit: "Fraqueza assimétrica em múltiplos miótomos — quadríceps, adutores, glúteos e tibial",
      sensory_pattern: "Dor intensa com distribuição não-dermatomal, perda sensorial multissegmentar",
      reflex_change: "Reflexo patelar e aquileu diminuídos bilateralmente",
      mechanism: "Diabetes mellitus (amiotrofia diabética), neoplasia pélvica, hematoma do psoas",
      diagnosis: "Plexopatia Lombossacral",
      nerve: "Plexo Lombossacral",
      root: "L1-S3",
      plexus_segment: "Plexo Lombossacral",
      compression_site: "Espaço retroperitoneal / pelve",
      explanation: "A plexopatia lombossacral (amiotrofia diabética ou síndrome de Bruns-Garland) apresenta dor intensa, fraqueza assimétrica e perda ponderal. Diferencia-se da radiculopatia por afetar múltiplos miótomos/dermátomos sem correlacionar com um único nível espinal. EMG é fundamental para diagnóstico.",
      options: ["Radiculopatia L4-L5", "Neuropatia Femoral", "Plexopatia Lombossacral", "Síndrome da Cauda Equina"],
      correct: "Plexopatia Lombossacral"
    }
  ],

  level4: [
    {
      id: "l4_01",
      level: 4,
      limb: "upper",
      title: "Dor Noturna no Punho",
      scenario: "Mulher de 48 anos, secretária, queixa de dor e parestesia noturna nas mãos, acordando do sono. Piora ao segurar o volante. Atrofia tenar leve. Teste de Phalen positivo em 30 segundos. Tinel positivo no punho.",
      motor_deficit: "Fraqueza na oponência do polegar, atrofia tenar",
      sensory_pattern: "Parestesia nos 3,5 dedos laterais (polegar, indicador, médio, metade anular)",
      reflex_change: "Sem alteração reflexa",
      mechanism: "Compressão do nervo mediano sob o retináculo dos flexores",
      diagnosis: "Síndrome do Túnel do Carpo",
      nerve: "Nervo Mediano",
      root: "C6-T1",
      plexus_segment: "Fascículos lateral e medial",
      compression_site: "Túnel do carpo (sob o retináculo dos flexores)",
      next_step: "Eletroneuromiografia (ENMG)",
      explanation: "A STC é a síndrome de compressão mais comum. O nervo mediano é comprimido sob o retináculo dos flexores. Testes de Phalen (flexão do punho por 60s) e Tinel (percussão sobre o punho) têm sensibilidade moderada. ENMG confirma: aumento da latência distal motora e sensitiva. Tratamento: órtese noturna, corticoide, cirurgia.",
      options_diagnosis: ["Síndrome do Túnel do Carpo", "Síndrome do Túnel Cubital", "Radiculopatia C6", "Doença de Raynaud"],
      options_nerve: ["Nervo Mediano", "Nervo Ulnar", "Nervo Radial", "Nervo Musculocutâneo"],
      options_site: ["Túnel do carpo (punho)", "Túnel cubital (cotovelo)", "Sulco radial (úmero)", "Desfiladeiro torácico"],
      correct_diagnosis: "Síndrome do Túnel do Carpo",
      correct_nerve: "Nervo Mediano",
      correct_site: "Túnel do carpo (punho)"
    },
    {
      id: "l4_02",
      level: 4,
      limb: "upper",
      title: "Dor no Cotovelo com Déficit no 4º e 5º Dedos",
      scenario: "Homem de 35 anos, ciclista, refere parestesia no dedo mínimo e metade do anular há 3 meses. Sinal de Froment positivo. Tinel positivo no sulco do nervo ulnar. Piora ao manter o cotovelo fletido por longa duração.",
      motor_deficit: "Fraqueza nos músculos interósseos e hipotênares, sinal de Froment positivo",
      sensory_pattern: "Parestesia nos 1,5 dedos mediais e face medial da mão",
      reflex_change: "Sem alteração reflexa",
      mechanism: "Compressão do nervo ulnar no sulco olecraniano (cotovelo)",
      diagnosis: "Síndrome do Túnel Cubital",
      nerve: "Nervo Ulnar",
      root: "C8-T1",
      plexus_segment: "Fascículo medial",
      compression_site: "Túnel cubital (sulco do nervo ulnar, cotovelo)",
      next_step: "Eletroneuromiografia (ENMG)",
      explanation: "A síndrome do túnel cubital é a segunda síndrome de compressão mais comum. O nervo ulnar é comprimido no sulco olecraniano. Sinal de Froment: ao pinçar papel entre polegar e indicador, o polegar flete (FLP ativado por compensação). Piora com cotovelo fletido. Tratamento: órtese em extensão, transposição cirúrgica.",
      options_diagnosis: ["Síndrome do Túnel do Carpo", "Síndrome do Túnel Cubital", "Radiculopatia C8", "Lesão do Fascículo Medial"],
      options_nerve: ["Nervo Mediano", "Nervo Ulnar", "Nervo Radial", "Nervo Interósseo Anterior"],
      options_site: ["Túnel do carpo (punho)", "Túnel cubital (cotovelo)", "Canal de Guyon (punho)", "Axila"],
      correct_diagnosis: "Síndrome do Túnel Cubital",
      correct_nerve: "Nervo Ulnar",
      correct_site: "Túnel cubital (cotovelo)"
    },
    {
      id: "l4_03",
      level: 4,
      limb: "upper",
      title: "Paralisia do Sábado à Noite",
      scenario: "Homem de 28 anos acorda após festa com braço pendente e punho caído. Adormeceu com o braço sobre o encosto da cadeira. Sem dor no momento. Tríceps preservado. Reflexo braquiorradial ausente.",
      motor_deficit: "Wrist drop completo — incapacidade de extensão do punho e dedos. Tríceps preservado.",
      sensory_pattern: "Hipoestesia no dorso da mão e região anatômica da tabaqueira",
      reflex_change: "Reflexo braquiorradial ausente, tricipital preservado",
      mechanism: "Compressão do nervo radial no sulco radial (terço médio do úmero)",
      diagnosis: "Paralisia do Sábado à Noite (lesão do nervo radial no sulco espiral)",
      nerve: "Nervo Radial",
      root: "C5-C8",
      plexus_segment: "Fascículo posterior",
      compression_site: "Sulco espiral (radial) do úmero",
      next_step: "Eletroneuromiografia após 3 semanas",
      explanation: "A 'paralisia do sábado à noite' ocorre por compressão do nervo radial no sulco espiral durante sono profundo (álcool, sedativos). O ramo do tríceps é emitido proximalmente — sua preservação localiza a lesão distal à axila. O braquiorradial está comprometido (reflexo ausente). Prognóstico geralmente excelente: recuperação em 6-8 semanas.",
      options_diagnosis: ["Paralisia do Sábado à Noite", "Lesão do Fascículo Posterior", "Síndrome Interóssea Posterior", "Radiculopatia C7"],
      options_nerve: ["Nervo Mediano", "Nervo Ulnar", "Nervo Radial", "Nervo Axilar"],
      options_site: ["Axila (nervo radial)", "Sulco espiral do úmero", "Cotovelo (túnel radial)", "Punho (ramo superficial)"],
      correct_diagnosis: "Paralisia do Sábado à Noite",
      correct_nerve: "Nervo Radial",
      correct_site: "Sulco espiral do úmero"
    },
    {
      id: "l4_04",
      level: 4,
      limb: "lower",
      title: "Compressão na Cabeça da Fíbula",
      scenario: "Paciente de 55 anos, diabético, internado após cirurgia abdominal. Após longa imobilização em posição supina com perna cruzada, nota pé caído e incapacidade de dorsiflexão ao tentar caminhar. Sensibilidade plantar preservada.",
      motor_deficit: "Foot drop — incapacidade de dorsiflexão e eversão. Flexão plantar e inversão preservadas.",
      sensory_pattern: "Hipoestesia no dorso do pé e espaço interdigital 1-2. Planta preservada.",
      reflex_change: "Reflexos preservados (patelar e aquileu normais)",
      mechanism: "Compressão extrínseca do nervo fibular comum na cabeça da fíbula",
      diagnosis: "Síndrome de Compressão do Nervo Fibular na Cabeça da Fíbula",
      nerve: "Nervo Fibular Comum",
      root: "L4-S1",
      plexus_segment: "Divisão dorsal do isquiático",
      compression_site: "Cabeça da fíbula (colo da fíbula)",
      next_step: "Eletroneuromiografia — confirmar nível e tipo de lesão",
      explanation: "O nervo fibular comum é extremamente vulnerável na cabeça da fíbula por sua posição superficial. Diabéticos têm risco aumentado. A preservação da sensibilidade plantar e reflexos normais confirmam que o tibial está intacto. Diferencia-se de L5 pela preservação do glúteo médio e ausência de dor lombar. Prognóstico variável: remover causa + fisioterapia.",
      options_diagnosis: ["Radiculopatia L5", "Compressão do Nervo Fibular", "Lesão do Nervo Isquiático", "Síndrome Compartimental"],
      options_nerve: ["Nervo Tibial", "Nervo Fibular Comum", "Nervo Isquiático", "Nervo Femoral"],
      options_site: ["Cabeça da fíbula", "Túnel do tarso", "Fossa poplítea", "Grande forame isquiático"],
      correct_diagnosis: "Compressão do Nervo Fibular",
      correct_nerve: "Nervo Fibular Comum",
      correct_site: "Cabeça da fíbula"
    },
    {
      id: "l4_05",
      level: 4,
      limb: "upper",
      title: "Síndrome do Desfiladeiro Torácico",
      scenario: "Mulher de 32 anos, fisioterapeuta, refere dor e parestesia no braço ao elevar o membro acima da cabeça. Sinal de Adson positivo (diminuição do pulso radial com rotação e extensão da cabeça para o lado afetado). Atrofia hipotenar discreta.",
      motor_deficit: "Fraqueza nos músculos intrínsecos da mão, predominantemente hipotênares",
      sensory_pattern: "Parestesia na face medial do braço, antebraço e mão (4º-5º dedos)",
      reflex_change: "Reflexo ulnar pode estar diminuído",
      mechanism: "Compressão do plexo braquial e artéria subclávia entre costela cervical/músculo escaleno e primeira costela",
      diagnosis: "Síndrome do Desfiladeiro Torácico",
      nerve: "Tronco Inferior do Plexo Braquial",
      root: "C8-T1",
      plexus_segment: "Tronco Inferior",
      compression_site: "Desfiladeiro torácico (entre escaleno anterior/médio e primeira costela)",
      next_step: "RX cervical (costela cervical?), Doppler arterial, ENMG",
      explanation: "A SDT comprime C8-T1 no desfiladeiro (triângulo interescalênico). O sinal de Adson é específico para compressão vascular. Sintomas pioram com abdução do braço. Causas: costela cervical (presente em 0,5-1% da população), hipertrofia dos escalenos, má postura. Tratamento: fisioterapia postural, ressecção da costela cervical em casos refratários.",
      options_diagnosis: ["Paralisia de Klumpke", "Síndrome do Desfiladeiro Torácico", "Síndrome do Túnel Cubital", "Radiculopatia C8"],
      options_nerve: ["Nervo Ulnar", "Nervo Mediano", "Tronco Inferior do Plexo Braquial", "Fascículo Medial"],
      options_site: ["Túnel cubital (cotovelo)", "Canal de Guyon (punho)", "Desfiladeiro torácico", "Axila"],
      correct_diagnosis: "Síndrome do Desfiladeiro Torácico",
      correct_nerve: "Tronco Inferior do Plexo Braquial",
      correct_site: "Desfiladeiro torácico"
    }
  ]
};

export const LEVEL_CONFIG = {
  1: {
    title: "Nível 1 — Reconhecimento de Nervos Periféricos",
    subtitle: "Identifique o nervo lesado com base no déficit clínico",
    color: "#3B82F6",
    bgColor: "#EFF6FF",
    borderColor: "#BFDBFE",
    icon: "🧠",
    questions: 1,
    attempts: 3
  },
  2: {
    title: "Nível 2 — Dermátomos & Radiculopatias",
    subtitle: "Identifique a raiz nervosa e diferencie neuropatia de radiculopatia",
    color: "#8B5CF6",
    bgColor: "#F5F3FF",
    borderColor: "#DDD6FE",
    icon: "🗺️",
    questions: 2,
    attempts: 3
  },
  3: {
    title: "Nível 3 — Lesões de Plexo",
    subtitle: "Identifique o segmento do plexo lesado e o quadro clínico",
    color: "#F59E0B",
    bgColor: "#FFFBEB",
    borderColor: "#FDE68A",
    icon: "🔌",
    questions: 1,
    attempts: 3
  },
  4: {
    title: "Nível 4 — Síndromes de Compressão & Trauma",
    subtitle: "Diagnóstico completo: identificar síndrome, nervo e sítio de compressão",
    color: "#EF4444",
    bgColor: "#FEF2F2",
    borderColor: "#FECACA",
    icon: "🏥",
    questions: 3,
    attempts: 3
  }
};